### ISSUE TITLE
Add Keyword Scope to Model

### ISSUE THREAD

**Issue by bbatsche** [esensi/core#18]
The `FilterableRepositoryTrait` may not be ideal or flexible enough in all cases. For example, in my current project it would be ideal if if keyword search looked in both the searchable attributes of a model _or_ in a field within one of its relationships (specifically the newly added `users_fields` relationship in [`esensi/user`](/esensi/user)). Plus, building the query at the repository level exposes some query building logic that could be better encapsulated in the model (not saying this is bad or wrong, just that I think it would be cleaner in the model). Adding a `scopeContainingKeywords()` method on `Model` would allow individual models to override it as necessary, and could be done without having to dramatically alter the existing API.

**Comment by dalabarge** [comment]
Laravel 5.3 has a searchable trait or something like that that we'll need to not conflict with but yes I agree we need to handle this new thing a bit better. I would say that it's still a concern of the repository as it's not a singular model we're dealing with and instead the `UserRepository` could adapt it's logic in the `filterKeywords` method to handle this special case of the `UserField` model. I'm down for a `scopeContainingKeywords` scope as the underlying implementation but again, there's no one size fits all here so you'll have different trait implementations of the interface. Definitely an Esensi 1.0 feature and in the meantime I'd say go with overwriting `filterKeywords` method on the repo that needs the flexibility.
