### ISSUE TITLE
Esensi not compatible with Laravel 5.4 ?

### ISSUE THREAD

**Issue by snipertomcat** [esensi/core#25]
I've been trying for the last few hours to get Esensi installed into a Laravel 5.4 application and for some reason, composer is giving me a lot of weird dependency errors about the versions not being right. I though perhaps it was me or composer but I removed the .lock file numerous times and attempted many different combinations of version numbers (varying both Laravel's and Esensi's package version)--nothing is working. 

Here is a screenshot of the latest garble that composer threw up in my console window:

![image](https://cloud.githubusercontent.com/assets/2884398/23108237/4ce6c7e8-f6bf-11e6-9131-cf990c37a7ba.png)

If I'm doing something wrong please clue me in.

Thanks,

Jesse

**Comment by dalabarge** [comment]
Please try installing 0.6.0 tagged versions of esensi/core and esensi/model or esensi/loaders if you're using those. We've updated our tags to support ~5.1 which should work up to 5.4. These packages rely on very little Laravel directly so there may be some incompatibilities with specific 5.x versions. If you find those please report them or submit a PR. This should at least get you installed anyway. If it does please mark this issue as closed.
