### ISSUE TITLE
ReflectionException Error

### ISSUE THREAD

**Issue by rohanvakharia** [esensi/core#8]
I am using Laravel 5.1
While installing it is giving me error:

```
[ReflectionException]
Class html does not exist
```

**Comment by dalabarge** [comment]
You need to install the HTML facade dependencies for Laravel. These have been included by `composer.json` here but your Laravel install's `app.php` would need to include the Facade reference and the service provider. Follow the instructions at http://laravelcollective.com/docs/5.1/html

**Comment by rohanvakharia** [comment]
Thanks for the quick response @dalabarge. 
I was forgot to add the provider for the laravelcollation/html package.
